### ISSUE TITLE
Feedback for “部署 Halo 服务”

### ISSUE THREAD

**Issue by sprout-cooler** [zeabur/zeabur#122]
Service Crashed
Oops. There seems to be some errors occurred in this service.

Or this service is not listening on the port of environment variable $PORT.
Please contact the service owner to fix this issue.

**Comment by MichaelYuhe** [comment]
Could you provide more information? Did you follow the documentation?
https://docs.zeabur.com/marketplace/halo

**Comment by yuaanlin** [comment]
Please head to our official Discord technical support channel https://discord.gg/DrdGCvXEyY for further help, thank you.
