### ISSUE TITLE
Feedback for “部署 Halo 服务”

### ISSUE THREAD

**Issue by sprout-cooler** [zeabur/zeabur#123]
用户密码不对

**Comment by MichaelYuhe** [comment]
Could you provide more information? Did you follow the documentation?
https://docs.zeabur.com/marketplace/halo

**Comment by yuaanlin** [comment]
未来有问题的话麻烦您反馈至我们的 Discord 官方技术支持社区 https://discord.gg/DrdGCvXEyY 以获得更即时的协助，谢谢。
