### ISSUE TITLE
Feedback for “Plans”

### ISSUE THREAD

**Issue by hujf2** [zeabur/zeabur#129]
![image](https://github.com/zeabur/zeabur/assets/17247940/1ca183d5-608c-4406-ad13-2996c92da54b)

账号：419644560@qq.com

为什么老是这样， 搞的我无法新增更多的service

**Comment by MichaelYuhe** [comment]
您的银行卡被 Stripe 拒绝了，我这帮您解绑一下

**Comment by yuaanlin** [comment]
未来有问题的话麻烦您反馈至我们的 Discord 官方技术支持社区 https://discord.gg/DrdGCvXEyY 以获得更即时的协助，谢谢。
