### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by ishenxian** [zeabur/zeabur#134]
一直停留在 登陆界面

**Comment by MichaelYuhe** [comment]
您好，可以提供一下 Email 吗

**Comment by ishenxian** [comment]
> 您好，可以提供一下 Email 吗

ishenxian@qq.com

**Comment by ishenxian** [comment]
[Sign in with GitHub](https://github.com/login/oauth/authorize?client_id=Iv1.eb8b8a6402b888d3&redirect_uri=https://dash.zeabur.com/auth/github/callback)https://github.com/login/oauth/authorize?client_id=xxxxxxxxxxx&redirect_uri=https://dash.zeabur.com/auth/github/callback

**Comment by ishenxian** [comment]
终于登录正常了
