### ISSUE TITLE
wordpress上传文件失败

### ISSUE THREAD

**Issue by MoeXiaoHei** [zeabur/zeabur#138]
![image](https://github.com/zeabur/zeabur/assets/47111189/ccc7261e-5b3c-4203-9d3b-9d59d824fd32)
这个有办法解决吗

**Comment by yuaanlin** [comment]
我们未来会开放用户自行调整 php.ini 的功能！

cc @pan93412

**Comment by yuaanlin** [comment]
未来有问题的话麻烦您反馈至我们的 Discord 官方技术支持社区 https://discord.gg/DrdGCvXEyY 以获得更即时的协助，谢谢。
