### ISSUE TITLE
Feedback for “MySQL”

### ISSUE THREAD

**Issue by zengboin** [zeabur/zeabur#140]
MySQL 被 suspend 之后，再启动就无法连接了，也找不到连接信息

**Comment by yuaanlin** [comment]
您好，麻煩提供下項目 ID

**Comment by zengboin** [comment]
从URL地址里面拿到的：  648fe60eb79d6eceab2c2199

**Comment by yuaanlin** [comment]
@zengboin 您好，已经帮您处理好了。

未来有问题的话麻烦您反馈至我们的 Discord 官方技术支持社区 https://discord.gg/DrdGCvXEyY 以获得更即时的协助，谢谢。
