### ISSUE TITLE
Halo 如何更新？

### ISSUE THREAD

**Issue by LAGQWQ** [zeabur/zeabur#141]
应用中心的 Halo是`2.6.1`版本，但 Halo 已经更新到了`2.7.0`。新版本大幅优化了缓存速度，我希望可以更新到这个版本。该如何更新呢？  
![image](https://github.com/zeabur/zeabur/assets/112602213/36626fbb-cd09-4b4b-9ba0-5248f2c7d5c1)
另外，应用中心的`halo.json`似乎还是`2.6.1`

**Comment by yuaanlin** [comment]
Marketplace 服务目前还不支持更新，您有需要的话可以 Discord 联系我们手动帮您更新。

自动更新的功能正在开发中 cc @pan93412

**Comment by yuaanlin** [comment]
未来有问题的话麻烦您反馈至我们的 Discord 官方技术支持社区 https://discord.gg/DrdGCvXEyY 以获得更即时的协助，谢谢。
