### ISSUE TITLE
Typo on the "template" page

### ISSUE THREAD

**Issue by tszhong0411** [zeabur/zeabur#145]
![image](https://github.com/zeabur/zeabur/assets/75498339/d5d0616b-295b-425c-b81f-ac8c4299f2ad)

"创建新模板" to "創建新模板"

**Comment by itsalicelee** [comment]
感謝回饋，我們會修正一下！cc @MichaelYuhe

**Comment by MichaelYuhe** [comment]
已修复，感谢反馈！
