### ISSUE TITLE
upload_max_filesize如何修改  “部署 WordPress 服务”

### ISSUE THREAD

**Issue by SimonGino** [zeabur/zeabur#147]
不知道upload_max_filesize对应的环境变量是什么
<img width="577" alt="image" src="https://github.com/zeabur/zeabur/assets/68073491/a16056e9-839d-4a08-bc6c-c003cce446a7">

**Comment by MichaelYuhe** [comment]
We are working on this!

**Comment by pan93412** [comment]
新部署的 WordPress 都會是 10MB 了！
