### ISSUE TITLE
service crashed

### ISSUE THREAD

**Issue by Yuanzidan081** [zeabur/zeabur#149]
Dear zeabur team:

zeabur is a wonderful platform. I just deployed my project by zeabur last month, it worked very well at that time. However, when I opened it and redeplyed it today, I found that it went something wrong, it said 'service crashed'. It seems that I cannot find any solution in the zeabur documentation, so what should I do when I meet such a problem?

The issue is demonstrated in a picture whose link is https://pic4.zhimg.com/80/v2-f238800ef637fad81b75625706dfa366.png

Best,
Yuan

**Comment by MichaelYuhe** [comment]
Can you please provide your service id for us?

**Comment by MichaelYuhe** [comment]
Close issue due to inactivity
