### ISSUE TITLE
昨晚服务为啥会重启？

### ISSUE THREAD

**Issue by zyxelva** [zeabur/zeabur#154]
我在zeabur上部署了memos，但今儿早一打开，服务重启后回退到版本0.12.2，这是怎么回事？没出问题前，版本为0.14.1，而且现在网页也无法加载数据。因为现在API接口变更了很多。请协助解决下这个版本问题。另外，数据怎么导出？不然备份都无法进行。
Service ID应该是这个 6481acef866e6d39e64d5d8f

**Comment by yuaanlin** [comment]
您好，版本回退的问题是因为 [Memos 官方 Docker 镜像](https://hub.docker.com/r/neosmemo/memos/tags) 更新造成的，这边已经帮您修改版本到 0.14.1 了。

后续若有其他问题，麻烦到我们的 [官方 Discord 技术支持社区](https://discord.gg/DrdGCvXEyY) 反馈，感谢理解。

**Comment by zyxelva** [comment]
> 您好，版本回退的问题是因为 [Memos 官方 Docker 镜像](https://hub.docker.com/r/neosmemo/memos/tags) 更新造成的，这边已经帮您修改版本到 0.14.1 了。
> 
> 后续若有其他问题，麻烦到我们的 [官方 Discord 技术支持社区](https://discord.gg/DrdGCvXEyY) 反馈，感谢理解。

貌似要魔法才能去社区。GitHub还行
