### ISSUE TITLE
Feedback for “Get Started”

### ISSUE THREAD

**Issue by cerbenus** [zeabur/zeabur#168]
Hi,

Where does Zeabur deploy apps to? Where are those servers located?

**Comment by MichaelYuhe** [comment]
Now we deploy apps to our GCP server in Taiwan, and we are going to have some servers in US West this month

**Comment by cerbenus** [comment]
Sounds good. I didn't find this info in your docs. I think it makes sense to add it :)

**Comment by MichaelYuhe** [comment]
Sure, we will update our documentations later this week. Thanks for your suggestions. You can join our Discord Server to get updated when our new server is ready!
https://discord.gg/DrdGCvXEyY
