### ISSUE TITLE
Docker hub rate limit

### ISSUE THREAD

**Issue by neves** [zeabur/zeabur#192]
Getting this error trying to deploy:

`#3 ERROR: failed to copy: httpReadSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/oven/bun/manifests/sha256:456d511a28e648b028180b5c3b0f21b878626c0520647611c543ed075a974b89: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit`

**Comment by MichaelYuhe** [comment]
Sorry for the trouble, we are investing this issue now. You can join [our Discord community](https://discord.gg/DrdGCvXEyY) to get the most timely updates.

**Comment by pan93412** [comment]
We have verified that it has been fixed. If you encounter this issue again, feel free to re-open this issue!
