### ISSUE TITLE
php伪静态问题

### ISSUE THREAD

**Issue by qkqpttgf** [zeabur/zeabur#200]
我已经观察到，默认在文件不存在时会交由index.php处理。
但我想要的是，文件存在时也交由index.php处理，屏蔽外部对真实文件的访问。

我有试过 .htaccess 文件，但没有起作用。
我怎么才能自定义 rewrite rule ？

**Comment by pan93412** [comment]
Zeabur 使用 Nginx + PHP-FPM 服务 PHP 文件，不支持 `.htaccess`。之后我们会推出更改 Nginx 设置的功能，在此之前您可以先撰写 Dockerfile 并进行 Git 或 Prebuilt 部署。

若有其他问题，欢迎到 [Zeabur 的 Discord](https://discord.gg/DrdGCvXEyY) 询问。
