### ISSUE TITLE
php无法编辑php.ini

### ISSUE THREAD

**Issue by ZeusFunk** [zeabur/zeabur#202]
注意到php无法编辑php.ini导致无法添加一些extension,
默认是有 PDO 扩展，但是实际上在php项目中的 PDO 只能够解析sqlite数据库
希望能够默认的引入 PDO_MySQL  扩展

**Comment by yuaanlin** [comment]
php extension 可以在 composer.json 中声明，zbpack 在构建时会自动识别及引入哦。

```json
{
    "require": {
        "php": ">=5.3.6",
        "ext-pdo": "*",
        "ext-pdo_mysql": "*"
    },
}
```

如果有其他问题，请到 Zeabur 的官方 Discord 交流群 https://discord.zeabur.com/ 发帖，谢谢！
