### ISSUE TITLE
It includes a US$ 5 free credit per month?

### ISSUE THREAD

**Issue by ZeusFunk** [zeabur/zeabur#212]
不是5美刀的免费额度吗？为什么每个月还要收这35？
![IMG_0891](https://github.com/zeabur/zeabur/assets/133857915/f211c9a8-866d-4fa0-9238-bfe5feba7bf1)

**Comment by pan93412** [comment]
这部分是您 Dev Plan 的费用：https://zeabur.com/docs/zh-CN/billing/plans#%E5%BC%80%E5%8F%91%E8%80%85%E6%96%B9%E6%A1%88。

有其他问题欢迎到 Zeabur Discord 询问，可以得到更快的回应速度 → <https://discord.gg/BMtBfS9rhA>
