### ISSUE TITLE
一些小疑问

### ISSUE THREAD

**Issue by razonyang** [zeabur/zeabur#219]
你好，刚绑定了信用卡，不过我有几个小疑问。

1. 开发者方案是每月收取 $5吗？还是说和免费方案一样，超出 $5 的按使用量计费呢？
![image](https://github.com/zeabur/zeabur/assets/17720932/a751f66d-0f12-445c-a944-817039b2d327)
2. 管理面板是否会增加内存和 CPU 限制设置吗？
3. 是否可以设置每月支出的上限呢？比如 $10，超出后自动停止所有服务。

**Comment by pan93412** [comment]
1. 每月收取 $5 并提供每个月 $5 的免费额度，若超过则根据 [Zeabur 服务费率](https://zeabur.com/docs/zh-CN/billing/pricing#%E6%9C%8D%E5%8A%A1%E8%B4%B9%E7%8E%87) 进行收费。
2. 目前就是您在 pricing 看到的资源限制，尚未实现降低资源限制的功能。
3. 尚未实现。

有其他问题欢迎到 [Zeabur 的 Discord](https://discord.gg/DrdGCvXEyY) 询问！
