### ISSUE TITLE
My service is duplicated in Billing

### ISSUE THREAD

**Issue by Etcetera-Tech** [zeabur/zeabur#274]
![Screenshot_7](https://github.com/zeabur/zeabur/assets/64138263/704c2989-0844-4bf9-9182-45be31865b26)
![Screenshot_4](https://github.com/zeabur/zeabur/assets/64138263/d04a0ea2-b714-45db-8bd5-1b870773b234)
![Screenshot_6](https://github.com/zeabur/zeabur/assets/64138263/d8df538e-237e-476e-a49d-54b6b56a348a)
![Screenshot_5](https://github.com/zeabur/zeabur/assets/64138263/83abbacb-2daa-4f35-9b9e-ff5738e621c7)

Hello, 
I have two projects, each with one service.

But in the statistics of the service in my project db-frontend-api for some reason there are two services db-skype-bot and db-skype-bot-1, they count money in the same way. It feels like my service is simply duplicated by billing.

What is it and how to fix it? Screenshots in the attachment.

**Comment by MichaelYuhe** [comment]
Hey sorry for the trouble, I'm investigating this issue right now, and we'll do a refund if there is some extra costs.
BTW, you can join our Discord community so that we can help better. https://discord.gg/N86HFCPxAG

**Comment by MichaelYuhe** [comment]
We've fixed that issue now, sorry for your trouble

**Comment by Etcetera-Tech** [comment]
![Screenshot_8](https://github.com/zeabur/zeabur/assets/64138263/4f6d767b-ef77-4a81-a04b-a482b1249a1c)
Thanks, I can't see the difference yet, let's look at the stats tomorrow and I'll get back to you.

PS My ID 65608bb8e97b7be9b94582fa

**Comment by Etcetera-Tech** [comment]
![image](https://github.com/zeabur/zeabur/assets/64138263/a5cb545f-91dc-4475-95ec-15285daf46af)
Thanks, no more problems. The bug was fixed.
