### ISSUE TITLE
Missing public domain when exposing TCP service only.

### ISSUE THREAD

**Issue by la3rence** [zeabur/zeabur#286]
I was trying deploy this image `bencdr/code-server-deploy-container:latest` on Zeabur.

If exposing TCP traffic with port 8080, there'll be no public domain configuration (under Networking) in the service edit page - but HTTP works.

**Comment by yuaanlin** [comment]
This is expected behavior, if your service not exposing a http port, you cannot bind a domain on it.

For more technical support, please visit our Discord server at https://discord.zeabur.com/ , thank you!
