### ISSUE TITLE
Feedback for “方案”

### ISSUE THREAD

**Issue by cnjax** [zeabur/zeabur#336]
开发者方案每个月都有 US$ 5 的免付费额度：

这句话有一些歧义。只看帮助的话，以为是free的。

开发者方案费用为US$5/月，方案内包含US$ 5 的免付费资源使用额度：

**Comment by MichaelYuhe** [comment]
Pricing 页面已更新，对这个定价模型做了更清晰的解释，issue 就先关闭啦，后续问题和建议欢迎到 Discord 反馈
