### ISSUE TITLE
Front-end and back-end are the same repo

### ISSUE THREAD

**Issue by Undertone0809** [zeabur/zeabur#361]
How to handle situations where the front-end and back-end are in the same repo?

I use nextjs + Python to develop my web app, but I don't know how to deploy them in the same repo in zeabur.

**Comment by MichaelYuhe** [comment]
Hey you can set root directory for those services. For example, set /frontend for the front end service

**Comment by Undertone0809** [comment]
How to do if package.json and poetry.toml are in the same directory.
