### ISSUE TITLE
Cannot create 2 Redis in a project

### ISSUE THREAD

**Issue by Undertone0809** [zeabur/zeabur#377]
## ❓ Question

I have already created one redis and I still want to create more, but there was an error on it. It seems we cannot create 2 redis in a project？

![image](https://github.com/zeabur/zeabur/assets/72488598/46c1e6f1-cad6-4a3a-8f70-43e911ed7fe1)

![image](https://github.com/zeabur/zeabur/assets/72488598/fcfdd98e-5344-4e6e-8e4f-21aac5cbcdbb)

**Comment by MichaelYuhe** [comment]
It's due to the same service name, we're investigating the issue now cc @pan93412 
You can join our discord server for quicker support

**Comment by Undertone0809** [comment]
It seems we should add a judgement to create a new name if it contains the same name.

**Comment by pan93412** [comment]
We have implemented the necessary function to let you deploy multiple instances of a Prebuilt service.

Feel free to try it and give us the feedback :)

**Comment by pan93412** [comment]
Fixed by the constant and [private networking](https://zeabur.com/docs/deploy/private-networking).
