### ISSUE TITLE
linkwarden 可否支持下 ？

### ISSUE THREAD

**Issue by nasawz** [zeabur/zeabur#381]
这个书签服务很不错，颜值也很高。

https://github.com/linkwarden/linkwarden

**Comment by MichaelYuhe** [comment]
现已支持一键部署 Linkwarden
预览：https://linkwarden.zeabur.app/
模板：https://zeabur.com/templates/1E5ABT

**Comment by nasawz** [comment]
刚刚做了部署， 注册流程正常， 在登录界面输入用户名密码就报错了， 信息如下：

Server error
There is a problem with the server configuration.
Check the server logs for more information.

**Comment by MichaelYuhe** [comment]
好的，我排查看看

**Comment by MichaelYuhe** [comment]
<img width="713" alt="image" src="https://github.com/zeabur/zeabur/assets/63531512/71727b81-a310-45f3-9fe1-93e6050e65fd">
看起来是漏了一些环境变量，我这边修改一下

**Comment by MichaelYuhe** [comment]
最新的 Prebuilt 应该好了，也可以通过在旧的服务里的环境变量中加入以下变量来解决：

```
NEXTAUTH_SECRET=${PASSWORD}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
NEXTAUTH_URL=${ZEABUR_WEB_URL}
```

**Comment by nasawz** [comment]
加环境变量后，正常了！

**Comment by MichaelYuhe** [comment]
https://github.com/zeabur/zeabur/pull/384 
预设的 Prebuilt 也更新好了～
