### ISSUE TITLE
Failed to load module script: Expected a JavaScript module script but the index-ewOogIP5.ig:1 server responded with a MIhE type of "text/html". Strict MIlE type checking is enforced for module scripts per HT spec.

### ISSUE THREAD

**Issue by yaozongbin** [zeabur/zeabur#394]
## 🚀 Feature Request

Failed to load module script: Expected a JavaScript module script but the
index-ewOogIP5.ig:1
server responded with a MIhE type of "text/html". Strict MIlE type checking is enforced for module
scripts per HT spec.

## 🔈 Motivation
![e414af0d3d06ff28b0f558be895b1fd](https://github.com/zeabur/zeabur/assets/78633585/dd4294d6-7e72-4100-9652-cd1badd1dfd3)

**Comment by yuaanlin** [comment]
如果您从 GitHub Pages 迁移 Vite 项目到 Zeabur，请记得将 config 中的 `base` 栏位移除。因为 GitHub Pages 将你的页面部署在子路径下，但 Zeabur 是直接部署在域名的根路径上。

若有其他问题需要技术支持，请访问 https://zeabur.com/dc 与我们联系，谢谢。
