### ISSUE TITLE
Add Directus support

### ISSUE THREAD

**Issue by aa900031** [zeabur/zeabur#416]
## 🚀 Feature Request

Please add [Directus](https://directus.io) to Prebuilt Services.

The Direcuts is headless CMS build with Node.js and Vue, that provide a user friendly admin dashboard to manage the contents and flows

**Comment by MichaelYuhe** [comment]
Deploy Directus with one click through the template: https://zeabur.com/templates/1T0LSQ

**Comment by aa900031** [comment]
@MichaelYuhe Thank you again, and that temple is my contribution
