### ISSUE TITLE
求支持 libsql 的预构建镜像

### ISSUE THREAD

**Issue by nasawz** [zeabur/zeabur#494]
https://github.com/tursodatabase/libsql

**Comment by yuaanlin** [comment]
@pan93412 直接做模板吧

**Comment by pan93412** [comment]
Hi @nasawz – we have published the libSQL template. Would you mind to test if this is working? Thank you!

https://zeabur.com/templates/4HF7IE

**Comment by nasawz** [comment]
已经安装了，本地客户端连接正常～   感谢
