### ISSUE TITLE
Static deployment fail

### ISSUE THREAD

**Issue by QingYi-Studio** [zeabur/zeabur#497]
When doing a large static project deployment, there will be a strange direct failure, suspected to be a run timeout.

**Comment by pan93412** [comment]
Would you mind to open a ticket on Discord? http://zeabur.com/dc

**Comment by QingYi-Studio** [comment]
```
Initializing builder ...

Cloning source code from git ...

╔══════════════════════════════ Build Plan ═════════════════════════════╗

║ provider         │ static                                             ║

╚═══════════════════════════════════════════════════════════════════════╝

#1 [internal] load build definition from Dockerfile

#1 transferring dockerfile: 1.62kB done

#1 DONE 0.0s

#2 [internal] load .dockerignore

#2 transferring context: 2B done

#2 DONE 0.0s

#3 [internal] load build context

#3 transferring context: 244.23MB 5.0s

#3 transferring context: 365.56MB 7.6s done

#3 DONE 7.7s

#4 [1/1] COPY . /

#4 DONE 2.3s

#5 exporting to client tarball

#5 sending tarball

#5 sending tarball 4.2s done

#5 DONE 4.2s

Uploading static files ...
```

**Comment by QingYi-Studio** [comment]
> Would you mind to open a ticket on Discord? http://zeabur.com/dc

I don't have Discord

**Comment by pan93412** [comment]
I wonder if this is because of the timeout settings of our deployment, as you said. @yuaanlin what do you think?

**Comment by QingYi-Studio** [comment]
I also tried Vercel, which was successfully deployed.

**Comment by pan93412** [comment]
> I also tried Vercel, which was successfully deployed.

Would you mind to provide the service ID so we can investigate it further? Thank you!

**Comment by QingYi-Studio** [comment]
669f5d3d274e868a3f809335?envID=669f3f2b812c32a5722a1d36

**Comment by pan93412** [comment]
We have found the root cause and will deploy a fix soon. Thank you for reporting!

**Comment by QingYi-Studio** [comment]
😁

**Comment by QingYi-Studio** [comment]
@pan93412 This hasn't been fixed yet?

**Comment by QingYi-Studio** [comment]
At the same time, I just encountered the domain name that was added earlier, and it also showed `PROVISIONED`, but now it shows `INVALID_DNS`.

**Comment by QingYi-Studio** [comment]
My domain name resolution Settings are normal and unchanged.

**Comment by QingYi-Studio** [comment]
Sometimes it becomes `PROVISIONING` and then quickly becomes `INVALID_DNS`.

**Comment by QingYi-Studio** [comment]
projects/6686af104f05d8b735893607
services/669f3aad274e868a3f808f2c

**Comment by QingYi-Studio** [comment]
My switch from `cname` to `txt` didn't work either.

**Comment by pan93412** [comment]
> Sometimes it becomes `PROVISIONING` and then quickly becomes `INVALID_DNS`.

You should add both the records to your domain. Seems like you did not add them to your domain properly, since I cannot see them:

```bash
$ dig qingyi-cdn.top CNAME

; <<>> DiG 9.10.6 <<>> qingyi-cdn.top CNAME
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 26208
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;qingyi-cdn.top.			IN	CNAME

;; AUTHORITY SECTION:
qingyi-cdn.top.		120	IN	SOA	ns1.bdydns.cn. sa.dudns.com. 2018080123 3600 300 2592000 120

;; Query time: 116 msec
;; SERVER: 2001:b000:168::2#53(2001:b000:168::2)
;; WHEN: Fri Jul 26 10:42:03 CST 2024
;; MSG SIZE  rcvd: 104

$ dig qingyi-cdn.top TXT

; <<>> DiG 9.10.6 <<>> qingyi-cdn.top TXT
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 46716
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;qingyi-cdn.top.			IN	TXT

;; AUTHORITY SECTION:
qingyi-cdn.top.		120	IN	SOA	ns1.bdydns.cn. sa.dudns.com. 2018080123 3600 300 2592000 120

;; Query time: 130 msec
;; SERVER: 2001:b000:168::2#53(2001:b000:168::2)
;; WHEN: Fri Jul 26 10:42:06 CST 2024
;; MSG SIZE  rcvd: 104
```

Besides, you must complete the process of ISP registration before you can host for public use on this region.

**Comment by QingYi-Studio** [comment]
I tested and found that the build was still not successful.

Same as before, still stuck in `Uploading static files...`.

**Comment by pan93412** [comment]
> I tested and found that the build was still not successful.
> 
> Same as before, still stuck in `Uploading static files...`.

The problem lies on our side. We are still testing on it internally. The shipment may go out today, and I will share the details once everything is ready on our end.

Sorry for the delay! 😢 Currently the workaround is reducing the files of your repository.

**Comment by QingYi-Studio** [comment]
Ok, thanks very much.

**Comment by pan93412** [comment]
Sorry that we have not fixed this issue yet.

The main reason this occurred is that your service contains too many files (over 30,000), exceeding our route limit. We are still seeking a solution to handle such a large route.

Since a typical project does not contain 30,000 files, I would recommend reducing the number of files in your service.

**Comment by QingYi-Studio** [comment]
Could you refer to Vercel's routing mode?

**Comment by QingYi-Studio** [comment]
Or similar modes.

**Comment by QingYi-Studio** [comment]
I also hope that the Hexo blog can execute `hexo clean` once when it is built to prevent residual files from being created due to file name changes

**Comment by pan93412** [comment]
> I also hope that the Hexo blog can execute `hexo clean` once when it is built to prevent residual files from being created due to file name changes

We do not cache Hexo build artifacts. Therefore, running `hexo clean` is generally unnecessary. Would you mind to describe the issue you encountered?

**Comment by QingYi-Studio** [comment]
For example, I created an article with a file name called `a bc.md`.

I've since renamed it abc.md, and the a-bc.html file from the last build is still there and displayed on the page.

**Comment by pan93412** [comment]
That is weird. I suspect it is because of the edge caching. Did you enable Cloudflare on your domain?

**Comment by QingYi-Studio** [comment]
nope.

**Comment by QingYi-Studio** [comment]
I have used CTRL+SHIFT+R to force a refresh.

And I only used the ordinary version of Baidu analysis.

No NS is set.

**Comment by QingYi-Studio** [comment]
To be honest, I don't even have a cloudflare account.

**Comment by yuaanlin** [comment]
Please come to our Discord server for technical support, thank you.

请到我们的官方 Discord 频道获取进一步技术支持，谢谢。

https://zeabur.com/dc
