### ISSUE TITLE
我想部署app 但是沒有成功 error如下

### ISSUE THREAD

**Issue by github-world192** [zeabur/zeabur#516]
由於 Cookie「_gh_sess」處於跨網站環境中，「SameSite」又設定為「Lax」或「Strict」，已遭拒絕設定。
<img width="983" alt="Screenshot 2024-09-04 at 12 00 26 AM" src="https://github.com/user-attachments/assets/03b6f525-bccc-4891-93a7-9db9c503dcc9">

**Comment by MichaelYuhe** [comment]
您好，可以到我们的[官方 Discord 社区](https://zeabur.com/dc)发帖，我们会给予最及时的帮助

**Comment by yuaanlin** [comment]
請到 https://zeabur.com/dc 讓我們的技術支援團隊可以即時解決您的問題，謝謝。
