### ISSUE TITLE
Adding a CNMAE record on the root domain is denied by Porkbun

### ISSUE THREAD

**Issue by physicsSorcererKing** [zeabur/zeabur#527]
Adding a CNMAE record on the root domain is denied by Porkbun:

```
ERROR:
Sorry, you can't have a CNAME on the root domain. It violates RFC, will break things, and probably cause your own personal space time to collapse in on itself.

You probably want to use an ALIAS record instead.
```

Change record type to ALIAS doesn't help.

Can someone help me?

**Comment by pan93412** [comment]
How about flattening your CNAME? Use [`dig`](https://digwebinterface.com/) to retrieve the A records, and then update your root domain with that information.

![CleanShot 2024-10-15 at 01 21 08@2x](https://github.com/user-attachments/assets/e73974f7-6ead-428e-9dd4-12b5afa12aea)

**Comment by physicsSorcererKing** [comment]
> How about flattening your CNAME? Use [`dig`](https://digwebinterface.com/) to retrieve the A records of our CNAME, and then update your root domain with that information.

Thanks. But it doesn't work.
Root domain site still response code 404 not found.
Any site with subdomain is OK.

**Comment by yuaanlin** [comment]
@physicsSorcererKing Please come to our Discord server for technical support, thank you.

https://zeabur.com/dc
