### ISSUE TITLE
Feedback for “方案”

### ISSUE THREAD

**Issue by buoooou** [zeabur/zeabur#528]
I am a new subscriber. I have tried to deploy the project many times but failed. Please refund me. I don't use it anymore.
my account id is ：6713d0cab9abd885bddb4c97，email：769329489@qq.com

**Comment by buoooou** [comment]
I can't log into discord，and it doesn't matter, you can just get a refund.

**Comment by buoooou** [comment]
![Uploading Snipaste_2024-10-20_00-47-02.png…]()

**Comment by buoooou** [comment]
<img width="1360" alt="Snipaste_2024-10-20_00-47-02" src="https://github.com/user-attachments/assets/34862e09-21a3-4124-bdc5-e1f11634336d">

**Comment by pan93412** [comment]
Hi！你可以直接用中文询问～
方便说明一下是部署遇到什么问题吗？

如果是 Java 项目的启动问题，或许可以试试看 [手动配 Java 执行命令](https://zeabur.com/docs/zh-CN/guides/java)
Zeabur 的 Java 判断比较没有这么成熟 orz

**Comment by pan93412** [comment]
已经退款了。
