### ISSUE TITLE
今天突然无法登录zeabur网站？

### ISSUE THREAD

**Issue by wuyongwen** [zeabur/zeabur#72]
今天突然无法登录zeabur网站？
```
https://dash.zeabur.com/auth/github/callback?code=xxx
``` 
一直卡在这个空白页面

**Comment by itsalicelee** [comment]
请问您是使用哪个GitHub帐号登入呢？

**Comment by wuyongwen** [comment]
就是这个呀

**Comment by itsalicelee** [comment]
了解，我们这边排查一下状况，请您稍等一会

**Comment by wuyongwen** [comment]
> @wuyongwen 已经修复了，再麻烦您测试下🙏

还是不行，还是空白页面 😂

**Comment by itsalicelee** [comment]
> > @wuyongwen 已经修复了，再麻烦您测试下🙏
> 
> 还是不行，还是空白页面 😂

您现在还有遇到问题吗？方便看一下log有没有什么报错呢

**Comment by itsalicelee** [comment]
在经过排查后，我们推测是VPN的问题。在此提供您几个方法测试： 
1. 使用VPN
2. 若您原本已经有使用，可以换个VPN测试看看 
3. 将VPN改为全局模式，让所有请求都走VPN

**Comment by wuyongwen** [comment]
启用代理后可以了～

**Comment by wuyongwen** [comment]
gateway.zeabur.com 只有这个域名被墙了
