### ISSUE TITLE
部署后无法访问，报502错误

### ISSUE THREAD

**Issue by wuyongwen** [zeabur/zeabur#77]
您好， 我使用zeabur 部署了docker容器，默认端口为8090。 这个端口是不对外暴露的吗？绑定域名后只能对外提供80 ，443端口吗？

另外访问域名一直是502错误，但是容器内日志没有错误，能否帮忙查下日志。

另外：使用支付宝扫描二维码付款成功后页面跳转到了404页面。😂

**Comment by yuaanlin** [comment]
您需要将程序监听在 **环境变量** `PORT` 的端口上，才能正确暴露您的服务。

例如，如果您的服务是用 Node.js 开发的，则下列写法是错误的：

```
app.listen(8090)
```

您必须这样写才能正确暴露服务：

```
app.listen(process.env.PORT)
```

**Comment by MichaelYuhe** [comment]
至于支付返回页面 404 的问题，是我们支付服务提供商的 bug ，即将要替换服务商，就能解决这个问题了

**Comment by wuyongwen** [comment]
> 您需要将程序监听在 **环境变量** `PORT` 的端口上，才能正确暴露您的服务。
> 
> 
> 
> 例如，如果您的服务是用 Node.js 开发的，则下列写法是错误的：
> 
> 
> 
> ```
> 
> app.listen(8090)
> 
> ```
> 
> 
> 
> 您必须这样写才能正确暴露服务：
> 
> 
> 
> ```
> 
> app.listen(process.env.PORT)
> 
> ```

我是使用Dockerfile部署的，[Dockerfile](https://github.com/wuyongwen/halo/blob/pub/publish/Dockerfile)

其中expose 8090 指定了暴露端口。

目前访问域名是502错误，我无法得到更多日志无法排查问题.

**Comment by yuaanlin** [comment]
您好，这个问题已经修复了，Zeabur 现在会自动根据 Dockerfile 内 expose 的端口自动向外映射。

如果您还有任何问题，请直接重新开启这个 issue 或到我们的 [Discord 交流群](https://discord.gg/DrdGCvXEyY) 获得更加即时的技术支持，谢谢。

**Comment by iamtsm** [comment]
> 您好，这个问题已经修复了，Zeabur 现在会自动根据 Dockerfile 内 `EXPOSE` 的端口自动向外映射。
> 
> 如果您还有任何问题，请直接重新开启这个 issue 或到我们的 [Discord 交流群](https://discord.gg/DrdGCvXEyY) 获得更加即时的技术支持，谢谢。

你好，请问这个自动向外映射支持多个端口吗，我部署之后，容器启动正常，但是无法访问
部署ID : 64cf6b93c640bb43db7d8551
