### ISSUE TITLE
springboot应用的多环境问题

### ISSUE THREAD

**Issue by xiguazhiPrince** [zeabur/zeabur#78]
我的springboot项目使用maven管理的，然后使用maven配置了多环境
一般来说打包和运行的时候命令行都会指定环境参数，但是在控制台好像毫无办法去传入构建和运行参数。
我能想到的解决方案
1. springboot项目接入配置中心，摒弃使用maven管理多环境
2. 使用docker，在控制台传入dockerfile需要的变量

官方有什么好办法吗？

**Comment by yuaanlin** [comment]
您好，我们这边后面可以将命令行参数设计成一个环境变量，让您从控制台注入

**Comment by xiguazhiPrince** [comment]
> 您好，我们这边后面可以将命令行参数设计成一个环境变量，让您从控制台注入

好的！迫切需要这个功能！现在使用maven管理的父子模块打包和多环境配置的springboot应用，没有办法使用seabur部署
