### ISSUE TITLE
无法登录 github账号callback后跳回login页面

### ISSUE THREAD

**Issue by RedhairHambagu** [zeabur/zeabur#80]
不是刚注册的，项目也建了，不小心登出后就没法进去了。
登录的是当前这个账号，使用了全局代理也无法登录，原有启动的项目还在正常运行，网站没有影响。
![image](https://user-images.githubusercontent.com/129669334/232073415-461c1b8d-6ba9-4351-af6c-b4c86bba4e06.png)

然后graphql 有返回值的第一个是这个
{
  "errors": [
    {
      "message": "not logged in",
      "extensions": {
        "code": "Unauthenticated"
      }
    }
  ],
  "data": null
}

我旧账号能够正常登录。

**Comment by MichaelYuhe** [comment]
您好，为防止部分用户的攻击以及滥用，Zeabur 暂时阻挡了 GitHub 注册时间小于一个月的用户登陆，希望您能理解。
如有需要可联系我们解禁：https://discord.gg/DrdGCvXEyY
