### ISSUE TITLE
Feedback for “域名绑定”

### ISSUE THREAD

**Issue by helianthuswhite** [zeabur/zeabur#83]
使用记录值为 zeabur.app 绑定自定义域名失败，访问不通

**Comment by MichaelYuhe** [comment]
方便截图看看配置吗？

**Comment by helianthuswhite** [comment]
> 方便截图看看配置吗？

<img width="1205" alt="image" src="https://user-images.githubusercontent.com/12878076/233401507-2b168479-4fb0-4c4a-8f1a-02c681b70722.png">

**Comment by helianthuswhite** [comment]
在zeabur里勾选了，redirect之后就好使了，可以在文档里更新一下

**Comment by yuaanlin** [comment]
> 在zeabur里勾选了，redirect之后就好使了，可以在文档里更新一下

好的，感谢反馈！ 未来有任何问题欢迎到我们的 [Discord 交流群](https://discord.gg/DrdGCvXEyY) 获得更即时的技术支持 👍
